### ISSUE TITLE
Still works? How can I run?

### ISSUE THREAD

**Issue by joaochris** [xorbit/MeetingMedia#2]
I have no idea how to make this work.

**Comment by xorbit** [comment]
Hi, I updated it to work with the current wol.jw.org update and added a README to show how to use it.

**Comment by joaochris** [comment]
@xorbit Thanks! It helped a lot! I had a problem. The downloads appeared as a file, but I renamed the extension to .jpg and it worked. A doubt. Is it possible to download videos too?

**Comment by xorbit** [comment]
I experimented with videos a while back when tv.jw.org was still separate and it didn't work with that site because it pretty much ran completely on Javascript.  Now this is integrated with jw.org it may work better but I have not found the time to look into it.
Contributions are welcome if someone can make it work. :)

**Comment by livrasand** [comment]
How can I run this on Windows?

**Comment by xorbit** [comment]
I just tried to run it on Linux with node v14.17.3 and it doesn't seem to work anymore.  There were also a good number of warnings about dependencies that are outdated when I installed the dependencies:

```
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile 
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile 
npm WARN deprecated uuid@3.3.3: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated har-validator@5.1.3: this library is no longer supported
npm WARN deprecated request@2.88.0: request has been deprecated, see https://github.com/request/request/issues/3142

added 79 packages, and audited 80 packages in 7s

7 vulnerabilities (1 moderate, 4 high, 2 critical)
```

Since I don't use the software myself anymore, you should consider it abandoned.  I do not have the time currently to keep it up to date since I don't use it myself anymore, but if someone wants to keep it up to date it can be forked and I do accept pull requests if someone wants to put time into it.
